spring.datasource.url=jdbc:mysql://localhost:3306/order_management
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kp480749@gmail.com
spring.mail.password=lrpk fiex rlfa nqan
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.cors.allowed-origins=http://localhost:5173
